spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/emarket
    username: postgres
    password: qwerty
  flyway:
    baseline-on-migrate: true
  mvc:
    view:
      prefix:  classpath:/templates/
      suffix: .html
  application:
    name: emarket
  security:
    user:
      name: mradmin
      password: qwerty
      roles: admin
