spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/emarket
    username: postgres
    password:
  flyway:
    baseline-on-migrate: true