spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/emarket
    username: postgres
    password: qwerty
  flyway:
    baseline-on-migrate: true
  mvc:
    view:
      prefix:  classpath:/templates/
      suffix: .html